//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalItem
    {
        public int MedicalItemID { get; set; }
        public Nullable<int> MedicalItemsType { get; set; }
        public string PurchaseDate { get; set; }
        public string ExpirationDate { get; set; }
    
        public virtual MedicalItem1 MedicalItem1 { get; set; }
    }
}
